### PR TITLE
Adds reporting of the node's network health

### PR DESCRIPTION
**Pull request by DylanVerstraete**
Fixes: https://github.com/threefoldtech/tfexplorer/issues/61

### CODE REVIEW

**Comment by DylanVerstraete** [comment]
> @DylanVerstraete What do you think ?

I think having a button `show interfaces` and then a modal with all the interfaces in a list would be nice to have.

**Comment by DylanVerstraete** [comment]
@zaibon all the nodes that have the ndmz interface have a good config (that I know off on devnet). If there is no public ipv6 or ipv4 then there is no config and we cannot show what config they have?

**Comment by zaibon** [comment]
ha that's what the message is saying. Indeed if there is no ndmz at all then there is nothing to show. But do we show the ip address in case there is one but it is not correct (private ip instead of public or something like this ?)

**Comment by DylanVerstraete** [comment]
Yes, I added a case on the ip6 on the ndmz. But there is no possibility that there is a ipv4 configured and that it's not a good value imo. Also the same for the public ipv6 config.

**Pull request merged**
