### PR TITLE
Adding vuejs package example

### PR DESCRIPTION
**Pull request by waleedhammam**
resolves (https://github.com/threefoldtech/jumpscaleX_threebot/issues/76)
- backend readme:  https://github.com/threefoldtech/jumpscaleX_threebot/blob/development_vuejs_package/ThreeBotPackages/examples/vuejs/README.md

- fronend readme: https://github.com/threefoldtech/jumpscaleX_threebot/blob/development_vuejs_package/ThreeBotPackages/examples/vuejs/newproject/README.md

### CODE REVIEW

**Comment by xmonader** [comment]
Such a great job!! Thank you so much @waleedhammam

**Comment by jdelrue** [comment]
@waleedhammam @rkhamis @xmonader 

We cannot install NPM in a 3bot, it will increase memory footprint.

We have developed a way to include Vue.js packages without building, so that the source can indeed be added to the package without using webpack or any other binary.

@coeneivan is adding it to 3bot right now will soon be pull requested.

 Please always consult with KDS if you add external binaries, every binary will increase memory footprint.

**Comment by xmonader** [comment]
This is an example package for documentation purposes - won't be running in a production server by default anyhow- covering typical aspects for every 3bot package author.

feel free to update it with all of the relevant information or document your process.

> We have developed a way to include Vue.js packages without building, so that the source can indeed be added to the package without using webpack or any other binary.

that's already the case for all of our production packages in svelte

**Comment by jdelrue** [comment]
This is a very bad example, since NPM should not be in the 3bot at all. If you don't want this to end up in production we don't need examples from it.

More info about our Vue.JS approach: 

https://github.com/jimbertools/vue-apps/blob/master/Readme.md


Will be added to 3bot packages on monday.

**Comment by xmonader** [comment]
It's not `very bad`. I found only 1 mistake it assumes the existence of npm to build the the `html` directory while it should be only done on the developer machine, other than that nothing. that doesn't render the effort useless. 

all of the examples packages aren't to be meant to be used in production they're meant to teach you and other package authors how to write packages and how to write the frontend to the backend. If you want to improve things be my guest

**Pull request merged**
