### PR TITLE
Provisioning actors

### PR DESCRIPTION
**Pull request by ahmedelsayed-93**
#24

### CODE REVIEW

**Comment by despiegk** [comment]
still relevant?

**Comment by ashraffouda** [comment]
> still relevant?

Yes, I just added test and somefixes

**Comment by zaibon** [comment]
This PR still missed all the methods that the node needs to use to learn about reservations.
The only way to get a reservation now is using `reservation_get` which expect a reservation ID. 
This is not something a node can use. 

What is needed is a method that takes a nodeID and return all the reservation for this specific node.
In the current 0-OS implementation we use this method with 2 modes.
1. we ask the BCDB to send ALL the reservation ever created for a node. The node call once at boot so it can deploy all the reservation that are still valid.
2. we ask the BCDB to send only new reservations since the last time we call this method. This is done so we avoid sending a huge amount of data every time. In a perfect world we should have a publish/subscribe system but we're not there yet.

**Comment by zaibon** [comment]
Also this issue: https://github.com/threefoldtech/jumpscaleX_threebot/issues/29 needs to be solved for this task to be completed.

**Comment by zaibon** [comment]
Went over the code again and we're not there yet. 
The list_registration method is not ok. 0-OS should not be sent the full reservation object. But only the actual workload description. 
Also, the code doesn't check anywhere is the reservation is actually in the deploy state before sending it back. Any reservation that doesn't have the reservation state should not be sent to 0-OS.  Some for deleted reservation, they need to be skipped.

Still missing a method that allow 0-OS to get reservation that are marked to be deleted.

Still missing method to send result of a deployment back. Each provisioning of a workload will be associated with a result.

**Pull request merged**
