### PR TITLE
Development communityapp

### PR DESCRIPTION
**Pull request by BolaNasr**

### CODE REVIEW

**Comment by BolaNasr** [comment]
Chat-flow works good but i'm **BLOCKED**  on 3bot Login & oauth
because our community app need session have email and user from 3bot login 
we need to add chat Factory  again

**Comment by xmonader** [comment]
Not blocked anymore, I restored auth middleware.

**Comment by BolaNasr** [comment]
ChatFlow works good but still have problem on wiki 
still in progress

**Comment by BolaNasr** [comment]
Everything works good ( chatflow, wikis, tree and latest post of FFP)
Screenshot from 2019-12-10 13-11-52

**Comment by rkhamis** [comment]
I'll close this PR because infrastructure changed too drastically

**Pull request closed without merging**
